#####################
## Mail providers
#####################

# If you don't provide any thrid party provider information, the app will use a default MockProvider and print the email in the standard output.

# Provide your Mandrill API Key. Leave empty if you don't want to activate Mandrill.
mandrill.api_key=
# Provide your Sengrid username an password. Leave empty if you don't want to activate Sendgrid.
sendgrid.username=
sendgrid.password=